version: '3.1'

services:
  game:
    build: .
    ports:
      - 5000:5000
    container_name: game
    environment:
      PORT: 5000
      MYSQL_USER: root
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: Janmenjaya@12
      MYSQL_DATABASE: onlineChess
      MYSQL_PORT: 3306
      JWT_SECRET: asgf97q9g9G9G9GFA90saf0ag083h0ahg
      REDIS_HOST: redis
    restart: always
